$(document).ready(function(){

	$(".vase_img").hide();
		
		$("#vase_four").show();
			$("#vase_").click(function(){
				$("#vase_").hide();
				$("#vase_one").show();
			});
			$("#vase_one").click(function(){
				$("#vase_one").hide();
				$("#vase_two").show();
			});
			$("#vase_two").click(function(){
				$("#vase_two").hide();
				$("#vase_three").show();
			});
			$("#vase_three").click(function(){
				$("#vase_three").hide();
				$("#vase_four").show();
			});
			$("#vase_four").click(function(){
				$("#vase_four").hide();
				$("#vase_five").show();
			});
			$("#vase_five").click(function(){
				$("#vase_five").hide();
				$("#vase_").show();
			});

	$(".all_flowers").hide();

		$("#one_one").show();
			$("#one_one").click(function(){
				$("#one_one").hide();
				$("#one_two").show();
			});
			$("#one_two").click(function(){
				$("#one_two").hide();
				$("#one_three").show();
			});
			$("#one_three").click(function(){
				$("#one_three").hide();
				$("#one_four").show();
			});
			$("#one_four").click(function(){
				$("#one_four").hide();
				$("#one_five").show();
			});
			$("#one_five").click(function(){
				$("#one_five").hide();
				$("#one_six").show();
			});
			$("#one_six").click(function(){
				$("#one_six").hide();
				$("#one_seven").show();
			});
			$("#one_seven").click(function(){
				$("#one_seven").hide();
				$("#one_eight").show();
			});
			$("#one_eight").click(function(){
				$("#one_eight").hide();
				$("#one_nine").show();
			});
			$("#one_nine").click(function(){
				$("#one_nine").hide();
				$("#one_ten").show();
			});
			$("#one_ten").click(function(){
				$("#one_ten").hide();
				$("#one_eleven").show();
			});
			$("#one_eleven").click(function(){
				$("#one_eleven").hide();
				$("#one_twelve").show();
			});
			$("#one_twelve").click(function(){
				$("#one_twelve").hide();
				$("#one_thirteen").show();
			});
			$("#one_thirteen").click(function(){
				$("#one_thirteen").hide();
				$("#one_fourteen").show();
			});
			$("#one_fourteen").click(function(){
				$("#one_fourteen").hide();
				$("#one_fifteen").show();
			});
			$("#one_fifteen").click(function(){
				$("#one_fifteen").hide();
				$("#one_sixteen").show();
			});
			$("#one_sixteen").click(function(){
				$("#one_sixteen").hide();
				$("#one_seventeen").show();
			});
			$("#one_seventeen").click(function(){
				$("#one_seventeen").hide();
				$("#one_eighteen").show();
			});
			$("#one_eighteen").click(function(){
				$("#one_eighteen").hide();
				$("#one_nineteen").show();
			});
			$("#one_nineteen").click(function(){
				$("#one_nineteen").hide();
				$("#one_twenty").show();
			});
			$("#one_twenty").click(function(){
				$("#one_twenty").hide();
				$("#one_twentyone").show();
			});
			$("#one_twentyone").click(function(){
				$("#one_twentyone").hide();
				$("#one_one").show();
			});

		$("#two_seven").show();
			$("#two_seven").click(function(){
				$("#two_seven").hide();
				$("#two_eight").show();
			});
			$("#two_eight").click(function(){
				$("#two_eight").hide();
				$("#two_nine").show();
			});
			$("#two_nine").click(function(){
				$("#two_nine").hide();
				$("#two_ten").show();
			});
			$("#two_ten").click(function(){
				$("#two_ten").hide();
				$("#two_eleven").show();
			});
			$("#two_eleven").click(function(){
				$("#two_eleven").hide();
				$("#two_twelve").show();
			});
			$("#two_twelve").click(function(){
				$("#two_twelve").hide();
				$("#two_thirteen").show();
			});
			$("#two_thirteen").click(function(){
				$("#two_thirteen").hide();
				$("#two_fourteen").show();
			});
			$("#two_fourteen").click(function(){
				$("#two_fourteen").hide();
				$("#two_fifteen").show();
			});
			$("#two_fifteen").click(function(){
				$("#two_fifteen").hide();
				$("#two_sixteen").show();
			});
			$("#two_sixteen").click(function(){
				$("#two_sixteen").hide();
				$("#two_seventeen").show();
			});
			$("#two_seventeen").click(function(){
				$("#two_seventeen").hide();
				$("#two_eighteen").show();
			});
			$("#two_eighteen").click(function(){
				$("#two_eighteen").hide();
				$("#two_nineteen").show();
			});
			$("#two_nineteen").click(function(){
				$("#two_nineteen").hide();
				$("#two_twenty").show();
			});
			$("#two_twenty").click(function(){
				$("#two_twenty").hide();
				$("#two_twentyone").show();
			});
			$("#two_twentyone").click(function(){
				$("#two_twentyone").hide();
				$("#two_one").show();
			});
			$("#two_one").click(function(){
				$("#two_one").hide();
				$("#two_two").show();
			});
			$("#two_two").click(function(){
				$("#two_two").hide();
				$("#two_three").show();
			});
			$("#two_three").click(function(){
				$("#two_three").hide();
				$("#two_four").show();
			});
			$("#two_four").click(function(){
				$("#two_four").hide();
				$("#two_five").show();
			});
			$("#two_five").click(function(){
				$("#two_five").hide();
				$("#two_six").show();
			});
			$("#two_six").click(function(){
				$("#two_six").hide();
				$("#two_seven").show();
			});

		$("#three_eleven").show();
			$("#three_eleven").click(function(){
				$("#three_eleven").hide();
				$("#three_twelve").show();
			});
			$("#three_twelve").click(function(){
				$("#three_twelve").hide();
				$("#three_thirteen").show();
			});
			$("#three_thirteen").click(function(){
				$("#three_thirteen").hide();
				$("#three_fourteen").show();
			});
			$("#three_fourteen").click(function(){
				$("#three_fourteen").hide();
				$("#three_fifteen").show();
			});
			$("#three_fifteen").click(function(){
				$("#three_fifteen").hide();
				$("#three_sixteen").show();
			});
			$("#three_sixteen").click(function(){
				$("#three_sixteen").hide();
				$("#three_seventeen").show();
			});
			$("#three_seventeen").click(function(){
				$("#three_seventeen").hide();
				$("#three_eighteen").show();
			});
			$("#three_eighteen").click(function(){
				$("#three_eighteen").hide();
				$("#three_nineteen").show();
			});
			$("#three_nineteen").click(function(){
				$("#three_nineteen").hide();
				$("#three_twenty").show();
			});
			$("#three_twenty").click(function(){
				$("#three_twenty").hide();
				$("#three_twentyone").show();
			});
			$("#three_twentyone").click(function(){
				$("#three_twentyone").hide();
				$("#three_one").show();
			});
			$("#three_one").click(function(){
				$("#three_one").hide();
				$("#three_two").show();
			});
			$("#three_two").click(function(){
				$("#three_two").hide();
				$("#three_three").show();
			});
			$("#three_three").click(function(){
				$("#three_three").hide();
				$("#three_four").show();
			});
			$("#three_four").click(function(){
				$("#three_four").hide();
				$("#three_five").show();
			});
			$("#three_five").click(function(){
				$("#three_five").hide();
				$("#three_six").show();
			});
			$("#three_six").click(function(){
				$("#three_six").hide();
				$("#three_seven").show();
			});
			$("#three_seven").click(function(){
				$("#three_seven").hide();
				$("#three_eight").show();
			});
			$("#three_eight").click(function(){
				$("#three_eight").hide();
				$("#three_nine").show();
			});
			$("#three_nine").click(function(){
				$("#three_nine").hide();
				$("#three_ten").show();
			});
			$("#three_ten").click(function(){
				$("#three_ten").hide();
				$("#three_eleven").show();
			});

		$("#four_fifteen").show();
			$("#four_fifteen").click(function(){
				$("#four_fifteen").hide();
				$("#four_sixteen").show();
			});
			$("#four_sixteen").click(function(){
				$("#four_sixteen").hide();
				$("#four_seventeen").show();
			});
			$("#four_seventeen").click(function(){
				$("#four_seventeen").hide();
				$("#four_eighteen").show();
			});
			$("#four_eighteen").click(function(){
				$("#four_eighteen").hide();
				$("#four_nineteen").show();
			});
			$("#four_nineteen").click(function(){
				$("#four_nineteen").hide();
				$("#four_twenty").show();
			});
			$("#four_twenty").click(function(){
				$("#four_twenty").hide();
				$("#four_twentyone").show();
			});
			$("#four_twentyone").click(function(){
				$("#four_twentyone").hide();
				$("#four_one").show();
			});
			$("#four_one").click(function(){
				$("#four_one").hide();
				$("#four_two").show();
			});
			$("#four_two").click(function(){
				$("#four_two").hide();
				$("#four_three").show();
			});
			$("#four_three").click(function(){
				$("#four_three").hide();
				$("#four_four").show();
			});
			$("#four_four").click(function(){
				$("#four_four").hide();
				$("#four_five").show();
			});
			$("#four_five").click(function(){
				$("#four_five").hide();
				$("#four_six").show();
			});
			$("#four_six").click(function(){
				$("#four_six").hide();
				$("#four_seven").show();
			});
			$("#four_seven").click(function(){
				$("#four_seven").hide();
				$("#four_eight").show();
			});
			$("#four_eight").click(function(){
				$("#four_eight").hide();
				$("#four_nine").show();
			});
			$("#four_nine").click(function(){
				$("#four_nine").hide();
				$("#four_ten").show();
			});
			$("#four_ten").click(function(){
				$("#four_ten").hide();
				$("#four_eleven").show();
			});
			$("#four_eleven").click(function(){
				$("#four_eleven").hide();
				$("#four_twelve").show();
			});
			$("#four_twelve").click(function(){
				$("#four_twelve").hide();
				$("#four_thirteen").show();
			});
			$("#four_thirteen").click(function(){
				$("#four_thirteen").hide();
				$("#four_fourteen").show();
			});
			$("#four_fourteen").click(function(){
				$("#four_fourteen").hide();
				$("#four_fifteen").show();
			});

		$("#five_nineteen").show();
			$("#five_nineteen").click(function(){
				$("#five_nineteen").hide();
				$("#five_twenty").show();
			});
			$("#five_twenty").click(function(){
				$("#five_twenty").hide();
				$("#five_twentyone").show();
			});
			$("#five_twentyone").click(function(){
				$("#five_twentyone").hide();
				$("#five_one").show();
			});
			$("#five_one").click(function(){
				$("#five_one").hide();
				$("#five_two").show();
			});
			$("#five_two").click(function(){
				$("#five_two").hide();
				$("#five_three").show();
			});
			$("#five_three").click(function(){
				$("#five_three").hide();
				$("#five_four").show();
			});
			$("#five_four").click(function(){
				$("#five_four").hide();
				$("#five_five").show();
			});
			$("#five_five").click(function(){
				$("#five_five").hide();
				$("#five_six").show();
			});
			$("#five_six").click(function(){
				$("#five_six").hide();
				$("#five_seven").show();
			});
			$("#five_seven").click(function(){
				$("#five_seven").hide();
				$("#five_eight").show();
			});
			$("#five_eight").click(function(){
				$("#five_eight").hide();
				$("#five_nine").show();
			});
			$("#five_nine").click(function(){
				$("#five_nine").hide();
				$("#five_ten").show();
			});
			$("#five_ten").click(function(){
				$("#five_ten").hide();
				$("#five_eleven").show();
			});
			$("#five_eleven").click(function(){
				$("#five_eleven").hide();
				$("#five_twelve").show();
			});
			$("#five_twelve").click(function(){
				$("#five_twelve").hide();
				$("#five_thirteen").show();
			});
			$("#five_thirteen").click(function(){
				$("#five_thirteen").hide();
				$("#five_fourteen").show();
			});
			$("#five_fourteen").click(function(){
				$("#five_fourteen").hide();
				$("#five_fifteen").show();
			});
			$("#five_fifteen").click(function(){
				$("#five_fifteen").hide();
				$("#five_sixteen").show();
			});
			$("#five_sixteen").click(function(){
				$("#five_sixteen").hide();
				$("#five_seventeen").show();
			});
			$("#five_seventeen").click(function(){
				$("#five_seventeen").hide();
				$("#five_eighteen").show();
			});
			$("#five_eighteen").click(function(){
				$("#five_eighteen").hide();
				$("#five_nineteen").show();
			});

		$("#six_four").show();
			$("#six_four").click(function(){
				$("#six_four").hide();
				$("#six_five").show();
			});
			$("#six_five").click(function(){
				$("#six_five").hide();
				$("#six_six").show();
			});
			$("#six_six").click(function(){
				$("#six_six").hide();
				$("#six_seven").show();
			});
			$("#six_seven").click(function(){
				$("#six_seven").hide();
				$("#six_eight").show();
			});
			$("#six_eight").click(function(){
				$("#six_eight").hide();
				$("#six_nine").show();
			});
			$("#six_nine").click(function(){
				$("#six_nine").hide();
				$("#six_ten").show();
			});
			$("#six_ten").click(function(){
				$("#six_ten").hide();
				$("#six_eleven").show();
			});
			$("#six_eleven").click(function(){
				$("#six_eleven").hide();
				$("#six_twelve").show();
			});
			$("#six_twelve").click(function(){
				$("#six_twelve").hide();
				$("#six_thirteen").show();
			});
			$("#six_thirteen").click(function(){
				$("#six_thirteen").hide();
				$("#six_fourteen").show();
			});
			$("#six_fourteen").click(function(){
				$("#six_fourteen").hide();
				$("#six_fifteen").show();
			});
			$("#six_fifteen").click(function(){
				$("#six_fifteen").hide();
				$("#six_sixteen").show();
			});
			$("#six_sixteen").click(function(){
				$("#six_sixteen").hide();
				$("#six_seventeen").show();
			});
			$("#six_seventeen").click(function(){
				$("#six_seventeen").hide();
				$("#six_eighteen").show();
			});
			$("#six_eighteen").click(function(){
				$("#six_eighteen").hide();
				$("#six_nineteen").show();
			});
			$("#six_nineteen").click(function(){
				$("#six_nineteen").hide();
				$("#six_twenty").show();
			});
			$("#six_twenty").click(function(){
				$("#six_twenty").hide();
				$("#six_twentyone").show();
			});
			$("#six_twentyone").click(function(){
				$("#six_twentyone").hide();
				$("#six_one").show();
			});
			$("#six_one").click(function(){
				$("#six_one").hide();
				$("#six_two").show();
			});
			$("#six_two").click(function(){
				$("#six_two").hide();
				$("#six_three").show();
			});
			$("#six_three").click(function(){
				$("#six_three").hide();
				$("#six_four").show();
			});

		$("#seven_nine").show();
			$("#seven_nine").click(function(){
				$("#seven_nine").hide();
				$("#seven_ten").show();
			});
			$("#seven_ten").click(function(){
				$("#seven_ten").hide();
				$("#seven_eleven").show();
			});
			$("#seven_eleven").click(function(){
				$("#seven_eleven").hide();
				$("#seven_twelve").show();
			});
			$("#seven_twelve").click(function(){
				$("#seven_twelve").hide();
				$("#seven_thirteen").show();
			});
			$("#seven_thirteen").click(function(){
				$("#seven_thirteen").hide();
				$("#seven_fourteen").show();
			});
			$("#seven_fourteen").click(function(){
				$("#seven_fourteen").hide();
				$("#seven_fifteen").show();
			});
			$("#seven_fifteen").click(function(){
				$("#seven_fifteen").hide();
				$("#seven_sixteen").show();
			});
			$("#seven_sixteen").click(function(){
				$("#seven_sixteen").hide();
				$("#seven_seventeen").show();
			});
			$("#seven_seventeen").click(function(){
				$("#seven_seventeen").hide();
				$("#seven_eighteen").show();
			});
			$("#seven_eighteen").click(function(){
				$("#seven_eighteen").hide();
				$("#seven_nineteen").show();
			});
			$("#seven_nineteen").click(function(){
				$("#seven_nineteen").hide();
				$("#seven_twenty").show();
			});
			$("#seven_twenty").click(function(){
				$("#seven_twenty").hide();
				$("#seven_twentyone").show();
			});
			$("#seven_twentyone").click(function(){
				$("#seven_twentyone").hide();
				$("#seven_one").show();
			});
			$("#seven_one").click(function(){
				$("#seven_one").hide();
				$("#seven_two").show();
			});
			$("#seven_two").click(function(){
				$("#seven_two").hide();
				$("#seven_three").show();
			});
			$("#seven_three").click(function(){
				$("#seven_three").hide();
				$("#seven_four").show();
			});
			$("#seven_four").click(function(){
				$("#seven_four").hide();
				$("#seven_five").show();
			});
			$("#seven_five").click(function(){
				$("#seven_five").hide();
				$("#seven_six").show();
			});
			$("#seven_six").click(function(){
				$("#seven_six").hide();
				$("#seven_seven").show();
			});
			$("#seven_seven").click(function(){
				$("#seven_seven").hide();
				$("#seven_eight").show();
			});
			$("#seven_eight").click(function(){
				$("#seven_eight").hide();
				$("#seven_nine").show();
			});

	$("#background1").click(function(){
		$("#background1").hide();
		$("#background2").show();
	});

	$("#background2").click(function(){
		$("#background2").hide();
		$("#background1").show();
	});

	$(document).click(function(){
		$(".message").hide();
	});
});